
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lost_found?serverTimezone=UTC
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.luerdao.entity
  configuration:
    map-underscore-to-camel-case: true
